### ISSUE TITLE
Comments to the manual

### ISSUE THREAD

**Issue by mzur** [DeepSeaCRU/BIIGLE-resources#3]
Hi! First of all, thank you for publishing your Ecologist's Guide. It's definitely one of the coolest resources created by the BIIGLE community so far! :muscle: 

Here is a list of comments I had while reading the guide. Feel free to incorporate them in the next version.

**Page 11:**
> Video files: need to be converted to MP4 format (codec 254).

The codec is called H.264. BIIGLE also supports the WebM format with the VP8, VP9 and AV1 codecs.

**Page 22:**
> To view the projects, click on the three lines on the top-right corner of the webpage, and select “Projects” in the drop-
down list, or just click on the projects tab.

I think you refer to the projects tab of the search page but this isn't clear.

**Page 23:**
> Double-click on the project of interest to open the volumes for each project.

A single click is enough :wink: 

**Page 26:**
> Annotation tools for video are mostly the same as that used for image annotation (see above), the exception is that you need to click the tick to accept the annotation before moving on to the next annotation.

You can also press <kbd>Enter</kbd> instead of clicking on the tick button.

**Page 29:**
> Sadly deleting the annotation session does not delete the annotations, which is a bit annoying when using for training.

Please open a new [discussion](https://github.com/orgs/biigle/discussions) to tell us more about your use case here. Would cloning the volume without annotations (see below) and then deleting the annotated volume be a solution here?

**Page 31:**
> To do this you need to select the ’force delete/re-label option on the top left of the screen.

This button is only available for project experts or admins. The default behavior of Largo (for project editors) is to replace the labels of the own user all the time, while only attaching labels to annotations of other users. Experts and admins can choose to also delete annotations/labels of other users using the button. If you think this is a bad default behavior, please [discuss](https://github.com/orgs/biigle/discussions) this with us.

**Page 38:**
> There is barely a description of what each command does, what input is expected...

The API documentation *should* provide an adequate explanation of the endpoint and the required input. Please help us to improve the documentation! Can you provide examples of the documentation of specific endpoints and how it could be improved (in a [discussion](https://github.com/orgs/biigle/discussions))?

**Page 38:**
> There is more going on behind the scenes, for example, this will only work if you have been granted access to the report you are requesting (granted to you by the creator of the project).

Actually, a report belongs only to a single user and (only) they can always download it. But the user needs access to a project/volume to be able to generate the report in the first place.

**Page 40:**
> You duplicate your volume. Take all or part of the annotation from one volume and add them to another without having to re-annotate the images

This is now a built-in feature of BIIGLE (as of yesterday)! It can be done via the user interface (in the project overview) or through a new [API endpoint](https://biigle.de/doc/api/index.html#api-Volumes-CloneVolume).

**Comment by Npiechaud** [comment]
Thanks for flagging all that @mzur, I have integrated your comments to the manual. Please tell us when you want more changes so this remains up to date.
